version: "3.8"

services:

  nginx:
    build:
      context: nginx
    restart: always
    container_name: nginx
    depends_on:
      - flask
    ports:
      - 3182:3182
      - 80:80
      - 443:443
    volumes:
      - "temp_homework_files:/usr/share/nginx/html/assets/temp_homework_files"
      - "/etc/letsencrypt/live/hatribute.de/fullchain.pem:/etc/letsencrypt/live/hatribute.de/fullchain.pem"
      - "/etc/letsencrypt/live/hatribute.de/privkey.pem:/etc/letsencrypt/live/hatribute.de/privkey.pem"

  flask:
    build: ./
    depends_on:
      - mariadb
    container_name: flask
    restart: always
    environment:
      APP_NAME: "hatribute_backend"
      MYSQL_DATABASE: "hatribute_db"
      MYSQL_USER: "hatribute_db"
      MYSQL_PASSWORD: "test"
      MYSQL_HOST: "mariadb"
      USE_PRODUCTION_DB: "true"
      TEMP_IMAGE_FOLDER: "temp_homework_files"
    expose:
      - 3182
    volumes:
      - "./logs:/app/logs"
      - "./homework:/app/homework"
      - "temp_homework_files:/app/temp_homework_files"

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD : test
      MYSQL_DATABASE : hatribute_db
      MYSQL_USER : hatribute_db
      MYSQL_PASSWORD : test
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306

volumes:
  db_data:
  temp_homework_files: